### ISSUE TITLE
Exception: Cannot Download File

### ISSUE THREAD

**Issue by prabhuSub** [chanon-kr/Shared_Function#1]
Hi,
I got an error after following all the steps following the below link. Any help?
[https://faun.pub/quick-etl-with-python-part-1-download-files-from-sharepoint-online-40bf23711662](https://faun.pub/quick-etl-with-python-part-1-download-files-from-sharepoint-online-40bf23711662)

```
Authen OK
<few logs for the exception>
Exception: Cannot Download File
```

**Comment by chanon-kr** [comment]
If you followed every steps in that article,

Can you test these?

1. Try to print the "download_path" variable, is it start with "/sites...." and end with your file's suffix? (for example ".pptx" for power point file)

2. When create object, try to change 
     -from "client_id" and "client_secret" 
     -to "user" = {your o365 email} and "password" = {your o365 password}
    If it can download, then it may because of some problems with the app user's permission. (Most of my cases are from this problem)


By the way, **thank you for your feedback**. 
This class is the first class I created which I found my bad coding from that time because of you.

if nothing works, try to uninstall the library and install the newest version directly from GitHub

```
pip uninstall py-topping -y
pip install git+https://github.com/chanon-kr/Shared_Function.git
```

And use the class "lazy_SP365" instead of "da_tran_SP365", this newest version will print the error message.

**Comment by prabhuSub** [comment]
Works like a charm. Thank you!
